name: Change File Permissions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  change-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Change file permissions
      run: chmod -R +x .

    - name: Commit changes
      run: |
        git config --global user.name "Maysara-nagy"
        git config --global user.email "maysara.nagy@gmail.com"
        git add .
        git commit -m "Set executable bit for all files" || echo "No changes to commit"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.A7A }}
      run: |
        git push origin HEAD:${{ github.ref }}
